/**
 * Types for Claude Session Manager
 */

export interface ClaudeSession {
    id: string;
    projectPath: string;
    startTime: Date;
    lastActivityTime: Date;
    messageCount: number;
    isActive: boolean;
    parentSessionId?: string;  // For forked sessions
    customName?: string;       // User-defined alias
    autoGeneratedName?: string; // AI-generated name based on content
    summary?: string;          // Brief summary of session content
}

export interface ClaudeMessage {
    sessionId: string;
    role: 'user' | 'assistant';
    content: string;
    timestamp: Date;
    toolUse?: ToolUse[];
}

export interface ToolUse {
    name: string;
    input: Record<string, unknown>;
}

export interface HistoryEntry {
    sessionId: string;
    type: string;
    message?: {
        role: string;
        content: string | ContentBlock[];
    };
    timestamp?: string;
    cwd?: string;
}

export interface ContentBlock {
    type: string;
    text?: string;
    name?: string;
    input?: Record<string, unknown>;
}

export interface SessionMetadata {
    customNames: Record<string, string>;  // sessionId -> custom name
    autoNames: Record<string, string>;    // sessionId -> auto-generated name
    summaries: Record<string, string>;    // sessionId -> summary
    forkRelations: Record<string, string>; // childId -> parentId
    archived: Record<string, boolean>;    // sessionId -> archived status
    customFolders: Record<string, string>; // sessionId -> custom folder name (overrides auto-detected)
}

export interface FlagOption {
    flag: string;
    label: string;
    description: string;
    type: 'boolean' | 'string' | 'select';
    options?: string[];  // For select type
    default?: string | boolean;
    category?: 'model' | 'permissions' | 'tools' | 'session' | 'advanced';
}

// Permission modes available in Claude CLI
export const PERMISSION_MODES = [
    { value: 'default', label: 'Default', description: 'Ask for permission on each action' },
    { value: 'acceptEdits', label: 'Accept Edits', description: 'Auto-accept file edits, ask for other actions' },
    { value: 'plan', label: 'Plan Mode', description: 'Research and plan only, no code changes' },
    { value: 'bypassPermissions', label: 'Bypass Permissions', description: 'Skip all permission prompts' },
    { value: 'delegate', label: 'Delegate', description: 'Delegate permission decisions to sub-agents' },
    { value: 'dontAsk', label: "Don't Ask", description: 'Never ask, deny actions that would need permission' }
] as const;

// Model options - using aliases for convenience
export const MODEL_OPTIONS = [
    { value: 'sonnet', label: 'Claude Sonnet', description: 'Fast and capable (default)' },
    { value: 'opus', label: 'Claude Opus', description: 'Most capable, best for complex tasks' },
    { value: 'haiku', label: 'Claude Haiku', description: 'Fastest, good for simple tasks' }
] as const;

export const AVAILABLE_FLAGS: FlagOption[] = [
    // Model selection
    {
        flag: '--model',
        label: 'Model',
        description: 'Which Claude model to use',
        type: 'select',
        options: MODEL_OPTIONS.map(m => m.value),
        default: 'sonnet',
        category: 'model'
    },

    // Permission modes
    {
        flag: '--permission-mode',
        label: 'Permission Mode',
        description: 'How to handle permission requests',
        type: 'select',
        options: PERMISSION_MODES.map(p => p.value),
        default: 'default',
        category: 'permissions'
    },
    {
        flag: '--dangerously-skip-permissions',
        label: 'Dangerously Skip All Permissions',
        description: 'Bypass ALL permission checks (use with extreme caution)',
        type: 'boolean',
        default: false,
        category: 'permissions'
    },

    // Tool restrictions
    {
        flag: '--allowedTools',
        label: 'Allowed Tools',
        description: 'Space-separated list of allowed tools (e.g. "Bash(git:*) Edit Read")',
        type: 'string',
        category: 'tools'
    },
    {
        flag: '--disallowedTools',
        label: 'Disallowed Tools',
        description: 'Space-separated list of denied tools (e.g. "Bash Edit")',
        type: 'string',
        category: 'tools'
    },
    {
        flag: '--tools',
        label: 'Available Tools',
        description: 'Specify available tools ("default" for all, "" for none, or list like "Bash,Edit,Read")',
        type: 'string',
        category: 'tools'
    },

    // Session options
    {
        flag: '--continue',
        label: 'Continue Last Session',
        description: 'Continue the most recent session in this directory',
        type: 'boolean',
        default: false,
        category: 'session'
    },
    {
        flag: '--resume',
        label: 'Resume Session ID',
        description: 'Resume a specific session by ID',
        type: 'string',
        category: 'session'
    },

    // Advanced options
    {
        flag: '--verbose',
        label: 'Verbose Output',
        description: 'Show verbose/debug output',
        type: 'boolean',
        default: false,
        category: 'advanced'
    },
    {
        flag: '--system-prompt',
        label: 'System Prompt',
        description: 'Custom system prompt for this session',
        type: 'string',
        category: 'advanced'
    },
    {
        flag: '--append-system-prompt',
        label: 'Append to System Prompt',
        description: 'Add to the default system prompt',
        type: 'string',
        category: 'advanced'
    },
    {
        flag: '--add-dir',
        label: 'Additional Directories',
        description: 'Extra directories to allow tool access to',
        type: 'string',
        category: 'advanced'
    }
];
